#!/usr/bin/env bash
set -e
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

source "$script_dir/runs/_functions.bash"

filter=""

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi
    shift
done

cd $script_dir

execute rsync -aurlv dot-config/ "${XDG_CONFIG_HOME:-$HOME/.config}"

scripts=$(find ./runs -maxdepth 1 -mindepth 1 -executable -type f | sort)

for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        log "filtering $script"
        continue
    fi

    execute $script
done
