#!/usr/bin/env bash
set -e

KEY_ID="john@coolpeople.io"

if gpg --list-secret-keys --keyid-format LONG | grep "$KEY_ID"; then
    echo "GPG secret key is present"
else
    echo "GPG secret key not present...importing $HOME/secret.key"
    cat $HOME/secret.key | gpg import
fi
