#!/usr/bin/env bash
set -e

mkdir -p $HOME/Projects
cd $HOME/Projects

if [ -d "$HOME/Projects/CRL" ]; then
    cd CRL
    git pull
else
    git clone git@gitea.coolpeople.io:Carnegie_Robotics/CRL.git
fi
