#!/usr/bin/env bash
set -e

# Ensure packer installed
packer_url="https://github.com/wbthomason/packer.nvim"
packer_dir="$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"

if [[ ! -d "$packer_dir" ]]; then
	mkdir -p $(dirname "$packer_dir")
	git clone --depth 1 $packer_url "$packer_dir"
else
	cd "$packer_dir"
	git pull
fi

